# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180727_1709'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goodsinfo',
        ),
    ]
