# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180727_1725'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeinfo',
            table='typeinfo',
        ),
    ]
