# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='upload')),
            ],
            options={
                'db_table': 'Img',
            },
        ),
        migrations.CreateModel(
            name='sweater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sweater',
            },
        ),
        migrations.CreateModel(
            name='sweaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sws_name', models.CharField(max_length=10)),
                ('sws_pic', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('sws_img', models.ImageField(null=True, upload_to='upload')),
                ('sws_img1', models.ImageField(null=True, upload_to='upload')),
                ('sws_img2', models.ImageField(null=True, upload_to='upload')),
                ('sws_introduction', models.CharField(max_length=2555)),
                ('sws_size', models.IntegerField()),
                ('sws_num', models.IntegerField()),
                ('sws_operate_time', models.DateTimeField(auto_now_add=True)),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.sweater')),
            ],
            options={
                'db_table': 'sweaters',
            },
        ),
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'women',
            },
        ),
        migrations.AddField(
            model_name='sweater',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.women'),
        ),
    ]
