# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_password', models.CharField(max_length=255)),
                ('s_operate_time', models.DateField(null=True)),
                ('s_emil', models.CharField(max_length=11)),
                ('s_ticket', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_name', models.CharField(max_length=10)),
                ('si_num', models.IntegerField()),
                ('si_sh', models.IntegerField()),
                ('si_img', models.ImageField(null=True, upload_to='upload')),
                ('si_pic', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('si_size', models.CharField(max_length=100)),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'Student_info',
            },
        ),
        migrations.CreateModel(
            name='StudentShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sis_name', models.CharField(max_length=10)),
                ('sis_num', models.IntegerField()),
                ('sis_sh', models.IntegerField()),
                ('sis_img', models.ImageField(null=True, upload_to='upload')),
                ('sis_pic', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('sis_size', models.CharField(max_length=100)),
                ('sis_zh', models.CharField(max_length=255)),
                ('sss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'Student_shop',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_url', models.CharField(max_length=30)),
                ('v_times', models.IntegerField()),
            ],
            options={
                'db_table': 'day7_visit',
            },
        ),
    ]
