# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'My_Role',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=30)),
                ('my', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.My_Role')),
            ],
            options={
                'db_table': 'MyUser',
            },
        ),
        migrations.CreateModel(
            name='Promission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Promission',
            },
        ),
        migrations.AddField(
            model_name='my_role',
            name='my_p',
            field=models.ManyToManyField(to='stu.Promission'),
        ),
    ]
