# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=40, verbose_name='密码')),
                ('uemail', models.CharField(max_length=30, verbose_name='电子邮箱')),
                ('ushow', models.CharField(default='', max_length=20, verbose_name='收件人名字')),
                ('uaddress', models.CharField(default='', max_length=100, verbose_name='收件地址')),
                ('uyoubian', models.CharField(default='', max_length=6, verbose_name='收件邮编')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='收件人电话')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
