# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180725_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='users_info',
        ),
    ]
