# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价钱')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('isTrue', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
            ],
            options={
                'verbose_name_plural': '发货管理',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='购买日期')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='是否付款')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总价')),
                ('oaddress', models.CharField(max_length=150, verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'verbose_name_plural': '订单管理',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='销量')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='销售额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
            ],
            options={
                'verbose_name_plural': '销量查看',
            },
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo'),
        ),
    ]
