# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.AlterModelTable(
            name='orderdetailinfo',
            table='orderdetailinfo',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='orderinfo',
        ),
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
    ]
